dist: xenial
language: python
sudo: true
addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11-postgis-2.5
      - postgresql-11-postgis-2.5-scripts
      - postgresql-client-11
matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO_VERSION=1.11 }
      - { python: "3.6", env: DJANGO_VERSION=2.2 }
      - { python: "3.6", env: DJANGO_VERSION=3.0 }
      - { python: "3.6", env: DJANGO_VERSION=3.1 }
before_install:
  - sudo -u postgres psql -c "CREATE USER testuser WITH PASSWORD 'password'"
  - sudo -u postgres psql -c "ALTER ROLE testuser SUPERUSER"

install:
  - pip install coverage
  - pip install coveralls
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2

before_script:
  - psql -U postgres -c "create extension postgis"
script:
  - coverage run --source=mapbox_location_field manage.py test
after_success:
  - coveralls